<?php

/**
 * @file
 * Hook implementations for Social Auth Facebook module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_facebook_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'social_auth_facebook.settings_form':
      $output = '<h3>' . t('Configuration instructions') . '</h3>';
      $output .= '<p>';
      $output .= t('Configuration instructions and other useful documentation can be found at the 
                 <a href="@documentation">Social Auth Facebook installation instructions</a>.', ['@documentation' => 'https://www.drupal.org/node/2936560']);
      $output .= '</p>';
      break;

  }

  return $output;
}
